### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Vincentvanleeuwen** [theonejonahgold/frontend-data#5]
**Readme**
- [x] Link naar je voorbeeld (img & link)

**Wiki**
- [x] Ik mis een wiki pagina waar je je concept aanpassingen uitlegd. (tenzij je concept niet is verandert natuurlijk)
- [x] Ik mis je proces in je wiki, wat heb je geleerd?
- [x] Update pattern
- [x] Data object before & after
- [x] Wat doe je met je incorrecte data?

**Demo**
- [x] Labels?
- [x] Transitions zouden een leuke toevoeging zijn!

Je bent lekker op weg Jonah! Als ik jou was zou ik nu even focussen op je wiki!

**Comment by jonahgoldwastaken** [comment]
Op de concept-pagina heb ik mijn proces uitgelicht, die heb ik nu ook overgenomen van mijn FP wiki waardoor alles bij elkaar zit
